name: Validate Feature with Codacy

on:
  push:
    branches:
      - 'feature/*'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build e Testes
      working-directory: ./app
      run: mvn clean verify

    - name: Create PR to Develop
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN }}
        base: develop
        branch: ${{ github.ref_name }}
        title: '${{ github.ref_name }} >>> develop'
