name: Deploy to PROD with Codacy

on:
  push:
    branches: [ "main" ]

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build e Testes
      working-directory: ./app
      run: mvn clean verify

    - name: Extrair nome do repositório
      run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

    - name: Gerar TAG da imagem
      run: |
        ENV=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')
        VERSION=$(date +%Y%m%d)-${{ github.run_number }}
        IMAGE_TAG="${ENV}-${VERSION}"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build Docker
      run: docker build -f ./app/Dockerfile -t nathanfiorito/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} .

    - name: Push Docker Image
      run: docker push nathanfiorito/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}

#    - name: Deploy to PROD
#      run: aws ecs update-service --cluster cluster-prod --service servico-prod --force-new-deployment
