name: Hotfix Deploy with Codacy

on:
  push:
    branches:
      - 'hotfix/*'

jobs:
  hotfix-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build e Testes
      working-directory: ./app
      run: mvn clean verify

    - name: Build Docker
      run: docker build -t seu-usuario/seu-app:hotfix .

    - name: Push Docker Image
      run: docker push seu-usuario/seu-app:hotfix

#    - name: Deploy Hotfix em PROD
#      run: aws ecs update-service --cluster cluster-prod --service servico-prod --force-new-deployment
